worker_processes auto;

events {
    worker_connections 1024;
}

http{
    limit_req_zone $binary_remote_addr zone=api:10m rate=10r/s;
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    gzip on;

    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;

    gzip_types
        text/css
        application/json
        application/javascript;

    upstream backend_pool {
        least_conn;

        server backend1:9090 max_fails=3 fail_timeout=30s;
        server backend2:9090 max_fails=3 fail_timeout=30s;
        server backend3:9090 max_fails=3 fail_timeout=30s;
    }

    server {
        listen 443 ssl;
        server_name _;

        server_tokens off;

        root /usr/share/nginx/html;
        index index.html;

        ssl_certificate /etc/nginx/certs/nginx_ssl.crt;
        ssl_certificate_key /etc/nginx/certs/nginx_ssl.key;
        ssl_protocols TLSv1.2 TLSv1.3;

        ssl_session_cache shared:SSL:10m;
        ssl_session_timeout 10m;

        ssl_prefer_server_ciphers on;

        add_header Referrer-Policy "strict-origin-when-cross-origin" always;
        add_header Referrer-Policy "strict-origin-when-cross-origin" always;

        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log warn;

        keepalive_timeout 65;
        keepalive_requests 100;

        location / {
            try_files $uri $uri/ /index.html;
        }
        location /api/ {
            proxy_pass http://backend_pool;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
            proxy_next_upstream_tries 3;
            limit_req zone=api_limit burst=20 nodelay;
        }
        location ~* \.(js|css)$ {
            expires 30d;
            add_header Cache-Control "public, immutable";
        }
    }
    server{
        listen 80;
        return 301 https://$host$request_uri;
    }
}

