services:
  backend1:
    image: risvanthkm/devops-task-backend:latest
    environment:
      HTTP_ADDR: ${HTTP_ADDR}
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable
      APP_SECRET: ${APP_SECRET}
    ports:
      - "9091:9090"
    restart: unless-stopped
    read_only: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    depends_on:
      db:
        condition: service_healthy
    mem_limit: 512m
    cpus: "1.0"
    

  backend2:
    image: risvanthkm/devops-task-backend:latest
    environment:
      HTTP_ADDR: ${HTTP_ADDR}
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable
      APP_SECRET: ${APP_SECRET}
    restart: unless-stopped
    ports:
      - "9092:9090"
    read_only: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    depends_on:
      db:
        condition: service_healthy
    mem_limit: 512m
    cpus: "1.0"
      
  backend3:
    image: risvanthkm/devops-task-backend:latest
    environment:
      HTTP_ADDR: ${HTTP_ADDR}
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable
      APP_SECRET: ${APP_SECRET}
    ports:
      - "9093:9090"
    restart: unless-stopped
    read_only: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    depends_on:
      db:
        condition: service_healthy
    mem_limit: 512m
    cpus: "1.0"

  frontend:
    image: risvanthkm/devops-task-frontend:latest
    environment:
      VITE_CLASS_ID: ${VITE_CLASS_ID}
    ports:
      - "80:80"
      - "443:443"
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - backend1
      - backend2
      - backend3
    mem_limit: 256m
    cpus: "1.0"

  db:
    image: postgres:17
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    security_opt:
      - no-new-privileges:true
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    mem_limit: 256m
    cpus: "1.0"

volumes:
  postgres_data:
