pipeline {
    agent any

    environment {
        DOCKERHUB_USERNAME = "risvanthkm"

        FRONTEND_IMAGE = "${DOCKERHUB_USERNAME}/devops-task-frontend"
        BACKEND_IMAGE  = "${DOCKERHUB_USERNAME}/devops-task-backend"

        IMAGE_TAG = "${env.BUILD_NUMBER}"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Frontend - Install Dependencies') {
            steps {
                dir('DevOPS_Task1/frontend') {
                    sh 'npm ci'
                }
            }
        }

        stage('Frontend - Install & Build') {
            steps {
                dir('DevOPS_Task1/frontend') {
                    sh '''
                    npm install
                    npm run build
                    '''
                }
            }
        }

        stage('Frontend - Test') {
            steps {
                dir('DevOPS_Task1/frontend') {
                    sh 'npm test -- --watchAll=false'
                }
            }
        }

        stage('Backend - Test') {
            steps {
                dir('DevOPS_Task1/backend') {
                    sh 'go test ./...'
                }
            }
        }

        stage('Build Docker Images') {
            steps {
                dir('DevOPS_Task1') {
                    sh """
                        docker build \
                            -t ${FRONTEND_IMAGE}:latest \
                            -t ${FRONTEND_IMAGE}:${IMAGE_TAG} \
                            ./frontend

                        docker build \
                            -t ${BACKEND_IMAGE}:latest \
                            -t ${BACKEND_IMAGE}:${IMAGE_TAG} \
                            ./backend
                    """
                }
            }
        }

        stage('Login to Docker Hub') {
            steps {
                dir('DevOPS_Task1/') {
                    withCredentials([
                        usernamePassword(
                            credentialsId: 'dockerhub',
                            usernameVariable: 'DOCKER_USER',
                            passwordVariable: 'DOCKER_PASS'
                        )
                    ]) {

                        sh '''
                        echo "$DOCKER_PASS" | docker login \
                            -u "$DOCKER_USER" \
                            --password-stdin
                        '''
                    }
                }
            }
        }

        stage('Push Docker Images') {
            steps {
                dir ('DevOPS_Task1'){
                    sh """
                        docker push ${FRONTEND_IMAGE}:latest
                        docker push ${FRONTEND_IMAGE}:${IMAGE_TAG}

                        docker push ${BACKEND_IMAGE}:latest
                        docker push ${BACKEND_IMAGE}:${IMAGE_TAG}
                    """
                }
            }
        }

        stage('Deploy') {
            when {
                branch 'main'
            }

            steps {
                dir ('DevOPS_Task1'){
                    sh '''

                    docker compose pull

                    docker compose up -d

                    docker image prune -f
                    '''
                }
            }
        }
        stage('Health Check') {
            steps {
                sh '''
                sleep 10
                curl --fail http://localhost
                '''
            }
}
    }

    post {

        success {
            echo "Pipeline completed successfully."
        }

        failure {
            echo "Pipeline failed."
        }

        always {
            cleanWs()
        }
    }
}